### ISSUE TITLE
Can't build on Ubuntu 18.04

### ISSUE THREAD

**Issue by photoniker** [itom-project/itom#69]
Trying to build itom on Ubuntu 18.04, getting error:

`../itom/sources/itom/DataObject/dataobj.cpp:3113: error: expected primary-expression before ‘>’ token
   _Tp* pt = (*((cv::Mat_<_Tp> *)(*dstMat))).ptr<_Tp>(y);`

[Issue created by M. Gronle: 2018-05-09]
[Last updated on bitbucket: 2018-05-10]

[Comment created by M. Gronle: 2018-05-10]
linux bugfix, fixes issue 69

→ <<cset c87084fc96b8>>
