### ISSUE TITLE
Failed Demo Func-Animation

### ISSUE THREAD

**Issue by photoniker** [itom-project/itom#194]
Demo Func-Animation “ func\_animation.py“ failed.  
Error Message: 'TimerItom' object has no attribute '\_timer'

[Issue created by Bernd Bertschinger: 2022-06-30]
[Last updated on bitbucket: 2022-07-08]

[Comment created by Bernd Bertschinger: 2022-07-08]
Fractal Issue from Release 4.1  -> resolved in 4.2

[Comment created by Bernd Bertschinger: 2022-07-08]
Sorry, for all the confusion. I have seen, that I was testing the wrong ITOM Version.  
I have downloaded RC3 and tested it. It works all fine now.  
Closing the ticket as resolved.

[Comment created by Johann Krauter: 2022-07-07]
For me this demos works with the RC3 version \(mpl 3.5.2\)

[Comment created by Bernd Bertschinger: 2022-07-07]
Still does not work.  
Updated the Itom default Matplotlib version from 3.3.4 to 3.5.2.  
  
Updating in the package manager, created a warning and an error:  
WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\\Program Files\\itom \(x64\)\\python3\\Scripts' which is not on PATH.   
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.  
ERROR: Could not install packages due to an OSError: \[WinError 5\] Zugriff verweigert: ‘c:\\\\program files\\\\itom \(x64\)\\\\python3\\\\lib\\\\site-packages\\\\matplotlib\\\\backends\\\\\_backend\_agg.cp38-win\_amd64.pyd'   
Consider using the \`--user\` option or check the permissions.  
  
Probably related to the fact that the folder and consequent subfolder of python3 are write protected   
  
But changing the write protection didn’t help in this case, becaus itom generated new write protected folders, which it could not change afterwards.  
Had to execute ITOM as administrator to update the matplotlib package.

Then tried to rerun fun\_acnimation.py but new error appeared:  
ImportError: cannot import name ‘StatusbarBase' from ‘matplotlib.backend\_bases' \(C:\\Program Files\\itom \(x64\)\\python3\\lib\\site-packages\\matplotlib\\backend\_bases.py\)  
  
I don’t understand how you can talk about a clean Windows installation, when you use matplotlib 3.5.2., when instead the RC is done with matplotlib 3.3.4?  
  
Shouldn’t the RC be delivered w. V.3.5.2 when it is clearly required? And should not all demos run w. the delivered packages?  
  
It is also strange for me, that python folders are all write protected. And that the package update fails.  
I don’t think this is an intended system behaviour.

[Comment created by Robin Hahn: 2022-07-05]
This Demo runs on a clean Windows 10  on a VM used itom 4.2 RC 1 with matplotlib 3.5.2

[Comment created by Bernd Bertschinger: 2022-07-01]
Complete Error Message:  
  
Traceback \(most recent call last\):

File "c:\\program files\\itom \(x64\)\\demo\\matplotlib\\func\_animation.py", line 23, in <module>

ani = FuncAnimation\(

File "C:\\Program Files\\itom \(x64\)\\python3\\lib\\site-packages\\matplotlib\\animation.py", line 1672, in \_\_init\_\_

TimedAnimation.\_\_init\_\_\(self, fig, \*\*kwargs\)

File "C:\\Program Files\\itom \(x64\)\\python3\\lib\\site-packages\\matplotlib\\animation.py", line 1430, in \_\_init\_\_

event\_source = fig.canvas.new\_timer\(interval=self.\_interval\)

File "C:/Program Files/itom \(x64\)/itom-packages\\mpl\_itom\\backend\_itom\_v3.py", line 533, in new\_timer

return TimerItom\(\*args, \*\*kwargs\)

File "C:/Program Files/itom \(x64\)/itom-packages\\mpl\_itom\\backend\_itom\_v3.py", line 160, in \_\_init\_\_

TimerBase.\_\_init\_\_\(self, \*args, \*\*kwargs\)

File "C:\\Program Files\\itom \(x64\)\\python3\\lib\\site-packages\\matplotlib\\backend\_bases.py", line 1093, in \_\_init\_\_

self.interval = 1000 if interval is None else interval

File "C:\\Program Files\\itom \(x64\)\\python3\\lib\\site-packages\\matplotlib\\backend\_bases.py", line 1135, in interval

self.\_timer\_set\_interval\(\)

File "C:/Program Files/itom \(x64\)/itom-packages\\mpl\_itom\\backend\_itom\_v3.py", line 185, in \_timer\_set\_interval

self.\_timer.setInterval\(self.\_interval\)

AttributeError: 'TimerItom' object has no attribute '\_timer'

Exception ignored in: <function TimerItom.\_\_del\_\_ at 0x0000020C21763280>

Traceback \(most recent call last\):

File "C:/Program Files/itom \(x64\)/itom-packages\\mpl\_itom\\backend\_itom\_v3.py", line 173, in \_\_del\_\_

TimerBase.\_\_del\_\_\(self\)

File "C:\\Program Files\\itom \(x64\)\\python3\\lib\\site-packages\\matplotlib\\backend\_bases.py", line 1098, in \_\_del\_\_

self.\_timer\_stop\(\)

File "C:/Program Files/itom \(x64\)/itom-packages\\mpl\_itom\\backend\_itom\_v3.py", line 191, in \_timer\_stop

self.\_timer.stop\(\)

AttributeError: 'TimerItom' object has no attribute '\_timer'

[Comment created by Bernd Bertschinger: 2022-07-01]
Error persists on clean Win10 distribution both as RM and VM.  
This problem looks mor severe.  
I therefore raise the priority for this issue.

[Comment created by Robin Hahn: 2022-07-01]
It works also with matplotlib 3.5.2. Was this issue produced by the RC Setup?

[Comment created by M. Gronle: 2022-06-30]
This demo works for me with matplotlib 3.5.1. I will try to update to 3.5.2…

Which version do you have?
