### ISSUE TITLE
QDropEvent methods

### ISSUE THREAD

**Issue by twip-os** [itom-project/itom#274]
In commit 3f85bb7cf53521847a694dcdb498b9c4fa9b4ff8 changed some calls on QDropEvent to prevent deprecation warnings, probably with QT6. But the new names throw errors with QT5.15.2.
Do we need a switch for the QT version here or is the deprecation warning acceptable?

Cheers
Thomas

**Comment by photoniker** [comment]
Since that still work with qt6.6.0 you dont`t need to switch qt6 version. There are some more deprecation warning which In started to fix in a branch.

**Comment by twip-os** [comment]
So we will revert the changes in the mentioned commit?

**Comment by photoniker** [comment]
Ah sorry I understand. Yes a version switch is necessary.

**Comment by photoniker** [comment]
Yes we can add a Version switch for qt5/6. But In don`t get an Error using qt5.15

**Comment by twip-os** [comment]
This is strange. The [documentation ](https://doc.qt.io/qt-6.2/qdropevent.html) states that "buttons", "modifiers" and "positions" are only there since 6.0.

**Comment by magro11** [comment]
@twip-os : which kind of errors did you mean? Compiler errors or anything else?

**Comment by twip-os** [comment]
Yes, compiler error caused by missing members:

> 5>C:\consignoDevelop\sources\itom\Qitom\widgets\scriptEditorWidget.cpp(1009,28): error C2039: 'position': is not a member of 'QDropEvent'
5>C:\consignoDevelop\3rdParty\Qt5.15.2\5.15.2\msvc2019_64\include\QtWidgets/qwidget.h(87): message : see declaration of 'QDropEvent'
5>C:\consignoDevelop\sources\itom\Qitom\widgets\scriptEditorWidget.cpp(1012,28): error C2039: 'buttons': is not a member of 'QDropEvent'
5>C:\consignoDevelop\3rdParty\Qt5.15.2\5.15.2\msvc2019_64\include\QtWidgets/qwidget.h(87): message : see declaration of 'QDropEvent'
5>C:\consignoDevelop\sources\itom\Qitom\widgets\scriptEditorWidget.cpp(1013,28): error C2039: 'modifiers': is not a member of 'QDropEvent'
5>C:\consignoDevelop\3rdParty\Qt5.15.2\5.15.2\msvc2019_64\include\QtWidgets/qwidget.h(87): message : see declaration of 'QDropEvent'
